<h1>Welcome To <?php echo $city; ?> Page </h1>
<form method="post" action="">

    <input type="submit" name="contr" value="Current weather">
    <input type="submit" name="contr" value="Forecast">
    <input type="submit" name="contr" value=" History">
    <input type="submit" name="contr" value="Time Zone">
    <input type="submit" name="contr" value="Sports">
    <input type="submit" name="contr" value="Astronomy">
    <input type="submit" name="contr" value="Weather Alerts">
    <input type="submit" name="contr" value="Air Quality">
</form>

<!-- Current Weather -->
<?php
if (isset($currentWeather)) {
    echo "<img src=https://" . substr($currentWeather->current->condition->icon, 2) . ">";
    echo "<h2>" . $currentWeather->location->name . "</h2><br>";
    echo "<h3>" . $currentWeather->location->region . "  " . $currentWeather->location->country . "</h3>";
    echo "<h3><b>Current:</b> Celsius:" . $currentWeather->current->temp_c . " Fahrenheit :" . $currentWeather->current->temp_f . "</h3>";
} ?>
<!-- Current weather -->

<!-- Forecast -->
<?php

if (isset($Forecast)) { ?>
<h2>Forecast Day Wise</h2>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Weather</th>
                <th scope="col">Date</th>
                <th scope="col">Min (C)</th>
                <th scope="col">Max (C)</th>
                <th scope="col">Average (C)</th>
        
            </tr>
        </thead>
        <tbody>
            <?php foreach ($Forecast as $key => $value) { 
            echo "<tr><th scope='row'><img src='https://".substr($value->day->condition->icon,2)."' ></th><td>".$value->day->condition->text."</td><td>".$value->date."</td><td>".$value->day->maxtemp_c."</td><td>".$value->day->mintemp_c."</td><td>".$value->day->avgtemp_c."</td> </tr>";
            } ?>

        </tbody>
    </table>
<?php } ?>
<!-- Time Zone -->
<?php if (isset($timeZone)) { ?>
 
<?php echo "<pre>";

print_r($timeZone->location->name."<br>");
print_r($timeZone->location->region."<br>");
print_r($timeZone->location->localtime)?>
<?php } ?>


<!-- Sports -->
<?php if (isset($sports)) { ?>
 
 <?php echo "<pre>";
 print_r($sports)?>
 <?php } ?>



<!-- Astronomy -->
<?php if (isset($astronomy)) { ?>
 
 <?php echo "<pre>";
 foreach($astronomy->astronomy->astro as $key=>$value)
 {
     echo "<h2>".$key." ->> ".$value ."</h2>";
 }
 ?>
 
 <?php } ?>


 <!-- weatherAlerts -->
<?php if (isset($weatherAlerts)) { ?>
 
 <?php echo "<pre>";

 if($weatherAlerts->alert)
{
    print_r($weatherAlerts->alert) ;
}
else {
    echo "No Data";
}

 ?>
 <?php } ?>


  <!-- Air Quality -->
<?php if (isset($airQuality)) { ?>
 
 <?php
 foreach($airQuality  as $key=>$value)
 {
     echo "<h2>".$key." :: ".$value ."</h2>";
 }?>
 <?php } ?>
 